name: "UpdateGSWikis"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 0'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run script
      run: python3 scripts/updateGSWikis.py

    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update nonGSWikis
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
